CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.EntityFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{

    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EfWriterRepository());

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WriterProfile()
        {
            return View();
        }

        public IActionResult WriterMail()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Test()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult WriterNavbrPartial()
        {
            return PartialView();
        }
        [AllowAnonymous]
        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult WriterEditProfile()
        {
            var writervalues = wm.TGetById(1);
            return View(writervalues);
        }
        [HttpPost]
        public IActionResult WriterEditProfile(Writer p)
        {
            WriterValidator wl = new WriterValidator();
            ValidationResult results = wl.Validate(p);
            if (results.IsValid)
            {
                wm.TUpdate(p);
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }

        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w = new Writer();
            if (p.WriterImage != null)
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/", newimagename);
                var stream = new FileStream(location, FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newimagename;
            }
            w.WriterMail = p.WriterMail;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = true;
            w.WriterAbout = p.WriterAbout;
            wm.TAdd(w);
            return RedirectToAction("Index", "Dashboard");
        }



    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}
    <h1>Burası Yazar Paneli</h1>

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>test</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <center>
                    <h1 class="card-title">Yazar Profili Düzenle</h1>
                </center>
                <br />

                @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })

                <div class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">Yazar Ad Soyad</label>

                        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">E Posta</label>
                        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Yazar Görsel</label>
                        <input type="file" name="WriterImage" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleTextarea1">Hakkında</label>
                    @Html.TextAreaFor(x => x.WriterAbout,10,3, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                <button class="btn btn-light">İptal</button>
            </div>
        </div>
    </div>

</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model EntitiyLayer.Concrete.Writer
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}



@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <center><h1 class="card-title">Yazar Profili Düzenle</h1></center>
                <br />

                @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })

                <form class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">Yazar Ad Soyad</label>

                        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">E Posta</label>
                        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                    </div>
                        <div class="form-group">
                        <label>Yazar Görsel</label>
                        <input type="file" name="img[]" class="file-upload-default">
                        <div class="input-group col-xs-12">
                            <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                            <span class="input-group-append">
                                <button class="file-upload-browse btn btn-gradient-primary" type="button">Resim Seç</button>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleTextarea1">İçerik</label>
                        @Html.TextAreaFor(x => x.WriterAbout, 10, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                    <button class="btn btn-light">İptal</button>
                </form>
            </div>
        </div>
    </div>
}

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
@*<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Tüm Hakları Saklıdır // @DateTime.Now.Year</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates </a> from Bootstrapdash.com</span>
    </div>
</footer>*@

CoreDemo/Views/Writer/WriterMail.cshtml
@{
    Layout = null;
}
 <h1>Yazar Mail</h1>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/Writer/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">David Greymaax</span>
                    <span class="text-secondary text-small">Yazılım Mühendisi</span>
                </div>

                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/ ">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-newspaper menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterMessage/">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterAdd/">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Login/WriterLogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout-variant menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>

CoreDemo/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}
<h1>Yazar Profil</h1>